/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCardModal: typeof import('./src/components/addCardModal.vue')['default']
    AddCardMoval: typeof import('./src/components/addCardMoval.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    Balance: typeof import('./src/components/Balance.vue')['default']
    BalanceCards: typeof import('./src/components/BalanceCards.vue')['default']
    BalanceInfo: typeof import('./src/components/BalanceInfo.vue')['default']
    CreditCard: typeof import('./src/components/CreditCard.vue')['default']
    Deposit: typeof import('./src/components/Deposit.vue')['default']
    DepositModal: typeof import('./src/components/DepositModal.vue')['default']
    Destinatario: typeof import('./src/components/Destinatario.vue')['default']
    Expenses: typeof import('./src/components/Expenses.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    InfoSection: typeof import('./src/components/InfoSection.vue')['default']
    InvestmentForm: typeof import('./src/components/InvestmentForm.vue')['default']
    InvestmentSummary: typeof import('./src/components/InvestmentSummary.vue')['default']
    MiddleLanding: typeof import('./src/components/MiddleLanding.vue')['default']
    MoneyCard: typeof import('./src/components/MoneyCard.vue')['default']
    Movements: typeof import('./src/components/movements.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    OldBalanceCards: typeof import('./src/components/OldBalanceCards.vue')['default']
    OperationButton: typeof import('./src/components/OperationButton.vue')['default']
    Payment: typeof import('./src/components/Payment.vue')['default']
    PaymentLinkModal: typeof import('./src/components/PaymentLinkModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Send: typeof import('./src/components/Send.vue')['default']
    SendModal: typeof import('./src/components/SendModal.vue')['default']
    TransactionHistory: typeof import('./src/components/TransactionHistory.vue')['default']
  }
}
