/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    BalanceCards: typeof import('./src/components/BalanceCards.vue')['default']
    CreditCard: typeof import('./src/components/CreditCard.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    InfoSection: typeof import('./src/components/InfoSection.vue')['default']
    InvestmentSummary: typeof import('./src/components/InvestmentSummary.vue')['default']
    MiddleLanding: typeof import('./src/components/MiddleLanding.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransactionHistory: typeof import('./src/components/TransactionHistory.vue')['default']
  }
}
