/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    Balance: typeof import('./src/components/Balance.vue')['default']
    BalanceCards: typeof import('./src/components/BalanceCards.vue')['default']
    CardWindows: typeof import('./src/components/CardWindows.vue')['default']
    Cobrar: typeof import('./src/components/Cobrar.vue')['default']
    CobrarForm: typeof import('./src/components/CobrarForm.vue')['default']
    CreditCard: typeof import('./src/components/CreditCard.vue')['default']
    Destinatario: typeof import('./src/components/Destinatario.vue')['default']
    Enviar: typeof import('./src/components/Enviar.vue')['default']
    EnviarForm: typeof import('./src/components/EnviarForm.vue')['default']
    Expense: typeof import('./src/components/Expense.vue')['default']
    FormularioEnvio: typeof import('./src/components/FormularioEnvio.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    InfoSection: typeof import('./src/components/InfoSection.vue')['default']
    Ingresar: typeof import('./src/components/Ingresar.vue')['default']
    InvestmentSummary: typeof import('./src/components/InvestmentSummary.vue')['default']
    Metodo: typeof import('./src/components/Metodo.vue')['default']
    MiddleLanding: typeof import('./src/components/MiddleLanding.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    TransactionHistory: typeof import('./src/components/TransactionHistory.vue')['default']
  }
}
